apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-reader
  namespace: demo
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-reader-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo
roleRef:
  kind: Role
  name: event-reader
  apiGroup: rbac.authorization.k8s.io
